name = "mcp-chat-interface"
main = "worker.ts"
compatibility_date = "2025-12-16"

[observability]
enabled = true

[[kv_namespaces]]
binding = "OPENAI_KEYS"
id = "4027568435684af29dcd2e0ffffc93c7"

[[durable_objects.bindings]]
name = "OAuthProviders"
class_name = "OAuthProviders"
script_name = "mcp-chat-interface"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["OAuthProviders"]